### ISSUE TITLE
HTTP requests frequently time out

### ISSUE THREAD

**Issue by haxtibal** [Icinga/icinga-powershell-restapi#3]
We initially noted timeouts when using the [checker endpoint](https://github.com/Icinga/icinga-powershell-apichecks) to invoke PS plugins via the API. But the issue is actually not specific to the checker API, but happens also when polling the main dispatcher.

Simple reproducer using [curl for Windows](https://curl.se/windows/).:
```
> While (1) { curl.exe -X GET "https://localhost:5668/v1" --insecure --max-time 10 }
... works a few times ...
curl: (28) Operation timed out after 10010 milliseconds with 0 bytes received
```
For us roughly each 10th request runs into timeout this way. Increasing the timeout does not change anything. During test, the While loop had exclusive access to the service, no concurrency involved.

**Comment by haxtibal** [comment]
With worker threads limited to 1 the timeout does _not_ occur
```
> Start-IcingaWindowsRESTApi -ConcurrentThreads 1
```
No solution, but probably useful information for further debugging.

**Comment by LordHepipud** [comment]
Thank you for the issue and the PR. I wasn't present as watcher on this repository, therefor it sadly slipped through.
I'm right now testing the PR and you were right. Running 25 checks now, I'm not receiving any timeouts so far and everything works a little smoother than before.

I will do some additional testing on more machines to get a better understanding if it works everywhere, but it seems to be fine.

**Comment by LordHepipud** [comment]
The fix in general works as expected and it not causing timeout issues anymore. However, either because of the fix or by another problem, there now seems to be a memory leak once this feature is enabled over time.

I'm currently trying to track down on there the leak is coming from.
